#!/bin/sh

# This normalization will also run check and fix routines
psfnormalize -v 3 -p checkfix=fix source/Narnoor-Regular.ufo

# Apply glyph data to Regular UFO
psfsetpsnames -i source/glyph_data.csv source/Narnoor-Regular.ufo
psfsetglyphorder -i source/glyph_data.csv source/Narnoor-Regular.ufo # --header sort_design

# Rebuild composites
psfbuildcomp -i source/composites.txt --colors g_yellow -n source/Narnoor-Regular.ufo

# Create WOFF metadata file
psfmakewoffmetadata -n narnoor -i org.sil.fonts -o source/Narnoor-WOFF-metadata.xml source/Narnoor-Regular.ufo

# Update FEA in UFO
psfmakefea -o source/Narnoor-Regular.ufo/features.fea -i source/master.feax -L last --omitaps "C" source/Narnoor-Regular.ufo
